### ISSUE TITLE
form values not set for radio buttons and check boxes

### ISSUE THREAD

**Issue by marcwmiller** [timcreative/light-bootstrap-dashboard-pro#23]
I'm seeing some interesting behavior with radio buttons and check boxes. When I click on the circle (or square) icons and submit a form, the value for those input elements are not set. However, if I click on the associated text in the label that surrounds the input element - the value gets set properly when the form is submitted.

I've attached a stripped down version of regular.html included in the examples/forms to demonstrate the behavior. 

First, try clicking the check box icon, and one of the radio icons (not the text) and click submit. In the browser console you don't see anything other than the message that the form was submitted:

`form submitted`

Next, refresh the browser window, and this time, click the text (not the icon) of the check box (Subscribe to newsletter) and one of the radio button text (First Radio or Second Radio). Click submit. You should see something similar:

`form submitted`
`newsCheck: check1`
`optionsRadios2: option2`

[regular - test case.zip](https://github.com/timcreative/light-bootstrap-dashboard-pro/files/1002214/regular.-.test.case.zip)

**Comment by dragosct10** [comment]
Hi @marcwmiller! This problem appears to you because the actual checkboxes and radios are working with javascript. For fixing this issue we removed the library for checkboxes and we build the checkboxes to work only with css. To achieve what we made for you please follow the next steps: 

1. First you must go in you're html page and you must to replace you're html code for checkboxes and radios with the following code:
```css
<div class="checkbox">
     <input id="checkbox1" type="checkbox">
     <label for="checkbox1">
          Example Checkbox
     </label>
</div>
                                      
<div class="radio">
     <input type="radio" name="radio1" id="radio5" value="option5" checked="">
     <label for="radio5">
          Example Radio
     </label>
</div>              
```

2. Now you have to take the uploaded scss partial `_checkbox-radio-switch.scss` and replace in `assets/scss/lbd/_checkbox-radio-switch.scss` with the new one.
[_checkbox-radio-switch.scss.zip](https://github.com/timcreative/light-bootstrap-dashboard-pro/files/1014332/_checkbox-radio-switch.scss.zip)

3. Third you have to go in `assets/js/bootstrap-checkbox-radio-switch-tags.js` and delete all until line: `250`. The Bootstrap-switch javascript code must remain there. 

4. Compile you're scss with [Koala](koala-app.com). Please be sure that you're output path is `assets/css/light-bootstrap-dashboard.css`.

**Comment by marcwmiller** [comment]
I apologize for my delayed response. I have implemented the steps you outlined and it works perfectly. Thank you very much.

**Comment by thinwaremedia** [comment]
So, does this mean that, by default, the framework specifically does not mark the checkboxes as checked when you click them? I've run into his as well, where I check the box on the page and the pretty checked box shows up but that field is never actually submitted with the form.

**Comment by freqout** [comment]
I've run into this as well. Was this purposely written to not actually trigger the input property? Seems weird to say "hey, we made your form prettier, but also, it's broken now."

**Comment by alexandru-paduraru** [comment]
@freqout no, the purpose was to trigger everything and work as the regular inputs, but it seems in the latest update there was a compatibility issue between the new browsers' updates, jQuery library and checkboxes/radios. The checkbox/radio library was working 100% a couple of months ago. 

We decided to remove completely the javascript triggers and moved completely to CSS. In this way, there will be no compatibility issues. This will come as an official update soon.

Hope this helps.

Best,
Alex

**Comment by lxlarcadelxl** [comment]
Hello Alex,
it would be nice if the download for the pro version on creative tim webpage gets updated.

I had 2 problems which took me a while.
- This one with the checkbox. It submits correctly if its pressed next to it not directly on it.
- If the Browserwindow get resized on a Datatable  the + for the collapsing columns (Actions for example) under each row is into the text of the first entry.

It would be very nice if the download files would be updated right after a fix. I wouldnt have run into the problems and spending so much useless time on it :(

Anyways i really like it ! Good job

Best regards
Marcus

**Comment by alexandru-paduraru** [comment]
@lxlarcadelxl yes, I understand your point and this our biggest priority at this moment, since we got over 30 products. We are working on an automatic system which will help us deploy to live (your downloadable files) right after we are doing a fix. The problem with this instant deploy is that you need some more tests in order to make sure you didn't destroy anything from other parts of the product. That why we choose to wait till we collect 5-10 bugs, we fix them, then we are doing all the checks. This process is taking always a couple of days for us to test on devices, browsers, platforms etc. That's why we cannot just release a fix instantly at this moment. 

We will have a solution for this soon. Can you please let me know your status now about the issues? Is there something that we can do to help?

Best,
Alex

**Comment by huseyintoz** [comment]
Hello,

@dragosct10  I have the same issue right now but I can not reach _checkbox-radio-switch.scss.zip file. When I click, it says not found. Can you help me? 

Thanks.

**Comment by dragosct10** [comment]
Hi, @huseyintoz! Please take the file from this [link](https://www.dropbox.com/s/x0veexmzbtiw6x1/_checkbox-radio-switch.scss?dl=0). 

Regards, 
Dragos
